docs:
  runs-on: ubuntu-latest
  needs: build
  steps:
    %checkout%
    %install%
    - uses: actions/cache@v2
      id: docs-cache
      name: Load webpack cache
      with:
        path: '.cache'
        key: ${{ runner.os }}-v4-${{ hashFiles('yarn.lock') }}
    - name: Build docs
      run: yarn build:docs
    - run: node .github/upload-preview.js public
      name: Upload docs
      if: always()

